class ParsedRtp:
    @property
    def version(self) -> int: ...
    @property
    def padding(self) -> bool: ...
    @property
    def extension(self) -> bool: ...
    @property
    def csrc_count(self) -> int: ...
    @property
    def marker(self) -> bool: ...
    @property
    def payload_type(self) -> int: ...
    @property
    def sequence_number(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def ssrc(self) -> int: ...
    @property
    def header_length(self) -> int: ...
    @property
    def payload(self) -> bytes: ...

def parse_rtp(data: bytes) -> ParsedRtp: ...
